import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Mulish } from "next/font/google";
import Footer from "./components/Footer";
import Head from "next/head"

const mulish = Mulish({
  weight: "400",
  subsets: ["latin"],
  display: "swap"
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en" className={mulish.className}>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <title>Home Page</title>
      </Head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
